import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import 'animate.css';
import { GlobalNavBar } from "@/components/global-nav-bar";
import { SideBar } from "@/components/side-bar";
import { Toaster } from "@/components/ui/sonner";
import Providers from "./Providers";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "poly-observer",
  description: "Generated by create next app",
  icons:'https://dct4life-files.s3.af-south-1.amazonaws.com/uploads/pologo.png'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` `}>
          <Providers>
            {children}
            <Toaster />
          </Providers>
        </body>
    </html>
  );
}
