/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ofME16E2Yv5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"
import { AlignVerticalJustifyStart, MoreHorizontal, Plus } from "lucide-react"
import { prisma } from "@/lib/connect"
import Link from "next/link"
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";
import { User } from "@prisma/client";
import { getQuoteOfTheDay } from "@/lib/getDailyQuote";

export async function DashboardCards() {

  const session:any = await getServerSession(authOptions);
  const user = session.user as User;

  const articleCount = await prisma.article.count()
  const departments = await prisma.department.count()
  const teamCount = await prisma.user.count({
    where: {
      email: {
        contains: "gmail",
      },
    },
  });

  const quotes = await prisma.quotes.findMany()
  const quote = getQuoteOfTheDay(quotes);

  return (
    <div className="m-6 px-4 bg-white  py-8 rounded-2xl sm:px-6 lg:px-8 dark:bg-[#1a1a1a]">
      <div>
        <h2 className="text-5xl font-bold text-black">Welcome {user.username.split(" ")[0]}</h2>
        <div className="bg-gray-100 rounded-2xl p-6 my-6 w-fit max-w-sm">
          <h2 className="font-bold text-[#B8860B] underline">Todays Quote</h2>
          <p className="text-black max-w-md ">
          &ldquo;{quote.content}&rdquo;
        </p>
        <p className="text-[red] text-xs">{quote.author}</p>
        </div>
        
      </div>
      <div className="flex gap-6 p-6 bg-gray-100 rounded-2xl">
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        <Card className="rounded-xl bg-[#007bff] dark:bg-[#0056b3] shadow-md hover:shadow-lg transition-shadow duration-300">
          <CardHeader className=" text-[#f0f0f0] p-4 rounded-t-md">
            <div className="flex items-center justify-between px-20 font-bold">
              <h2>Articles</h2>
            </div>
            
          </CardHeader>
          <CardContent className="flex justify-center p-4">
            <p className="font-bold text-white text-2xl">{articleCount}</p>
          </CardContent>
          <CardFooter>
            <div className="w-full flex justify-between items-center">
              <Link href={'/observer/blog/media-news/create'}>
              <Plus className="h-6 w-6 rounded-full p-2 bg-white bg-opacity-20 shadow-lg text-white" />
              </Link>
              <Link href={'/observer/media-news/blog'} className="px-5 py-2 bg-white bg-opacity-20 shadow-lg rounded-lg text-white font-bold text-xs">View</Link>
            </div>
          </CardFooter>
        </Card>
        <Card className="rounded-xl bg-[#28a745] dark:bg-[#1e7e34]shadow-md hover:shadow-lg transition-shadow duration-300">
        <CardHeader className=" text-[#f0f0f0] p-4 rounded-t-md">
            <div className="flex items-center justify-between px-20 font-bold">
              <h2>Team</h2>
            </div>
            
          </CardHeader>
          <CardContent className="flex justify-center p-4">
            <p className="font-bold text-white text-2xl">{teamCount}</p>
          </CardContent>
          <CardFooter>
            <div className="w-full flex justify-between items-center">
              <Link href={'/observer/team'}>
                <Plus className="h-6 w-6 rounded-full p-2 bg-white bg-opacity-20 shadow-lg text-white" />
              </Link>
              <Link href={'/observer/team/add'} className="px-5 py-2 bg-white bg-opacity-20 shadow-lg rounded-lg text-white font-bold text-xs">View</Link>
            </div>
          </CardFooter>
        </Card>
        <Card className="rounded-xl bg-[#dc3545] dark:bg-[#a71d2a] shadow-md hover:shadow-lg transition-shadow duration-300">
        <CardHeader className=" text-[#f0f0f0] p-4 rounded-t-md">
            <div className="flex items-center justify-between px-20 font-bold">
              <h2>Signups</h2>
            </div>
            
          </CardHeader>
          <CardContent className="flex justify-center p-4">
            <p className="font-bold text-white text-2xl">0</p>
          </CardContent>
          <CardFooter>
            <div className="w-full flex justify-between items-center">
              <AlignVerticalJustifyStart className="h-6 w-6 rounded-full p-2 bg-white bg-opacity-20 shadow-lg text-white" />
              <Link href={'/observer'} className="px-5 py-2 bg-white bg-opacity-20 shadow-lg rounded-lg text-white font-bold text-xs">View</Link>
            </div>
          </CardFooter>
        </Card>
        <Card className="rounded-xl bg-[#6c757d] dark:bg-[#495057] shadow-md hover:shadow-lg transition-shadow duration-300">
        <CardHeader className=" text-[#f0f0f0] p-4 rounded-t-md">
            <div className="flex items-center justify-between px-20 font-bold">
              <h2>Departments</h2>
            </div>
            
          </CardHeader>
          <CardContent className="flex justify-center p-4">
            <p className="font-bold text-white text-2xl">{departments}</p>
          </CardContent>
          <CardFooter>
            <div className="w-full flex justify-between items-center">
              <Link href={'/observer/department'}>
                <Plus className="h-6 w-6 rounded-full p-2 bg-white bg-opacity-20 shadow-lg text-white" />
              </Link>
              <Link href={'/observer/department'} className="px-5 py-2 bg-white bg-opacity-20 shadow-lg rounded-lg text-white font-bold text-xs">View</Link>
            </div>
          </CardFooter>
        </Card>
        <Card className="rounded-xl bg-black dark:bg-[#59359a] shadow-md hover:shadow-lg transition-shadow duration-300">
        <CardHeader className=" text-[#f0f0f0] p-4 rounded-t-md">
            <div className="flex items-center justify-between px-20 font-bold">
              <h2>Sponsors</h2>
            </div>
            
          </CardHeader>
          <CardContent className="flex justify-center p-4">
            <p className="font-bold text-white text-2xl">0</p>
          </CardContent>
          <CardFooter>
            <div className="w-full flex justify-between items-center">
              <Link href={'/observer/'}>
                <Plus className="h-6 w-6 rounded-full p-2 bg-white bg-opacity-20 shadow-lg text-white" />
              </Link>
              <Link href={'/observer'} className="px-5 py-2 bg-white bg-opacity-20 shadow-lg rounded-lg text-white font-bold text-xs">View</Link>
            </div>
          </CardFooter>
        </Card>
        <Card className="rounded-xl bg-[purple] dark:bg-[#59359a] shadow-md hover:shadow-lg transition-shadow duration-300">
        <CardHeader className=" text-[#f0f0f0] p-4 rounded-t-md">
            <div className="flex items-center justify-between px-20 font-bold">
              <h2>Subscribers</h2>
            </div>
            
          </CardHeader>
          <CardContent className="flex justify-center p-4">
            <p className="font-bold text-white text-2xl">2</p>
          </CardContent>
          <CardFooter>
            <div className="w-full flex justify-between items-center">
              <Link href={'/observer/'}>
                <Plus className="h-6 w-6 rounded-full p-2 bg-white bg-opacity-20 shadow-lg text-white" />
              </Link>
              <Link href={'/observer'} className="px-5 py-2 bg-white bg-opacity-20 shadow-lg rounded-lg text-white font-bold text-xs">View</Link>
            </div>
          </CardFooter>
        </Card>
      </div>
      <img src="https://t3.ftcdn.net/jpg/02/92/36/74/360_F_292367471_Ix2ekPQcg9Xc9bWCj3pCvzgVn3INuqm2.jpg" alt="sponsor" className="max-w-lg" />
      </div>
     
    </div>
  )
}

function BarChartIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  )
}


function CalendarIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function NewspaperIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 22h16a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v16a2 2 0 0 1-2 2Zm0 0a2 2 0 0 1-2-2v-9c0-1.1.9-2 2-2h2" />
      <path d="M18 14h-8" />
      <path d="M15 18h-5" />
      <path d="M10 6h8v4h-8V6Z" />
    </svg>
  )
}


function UserIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function VideoIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5" />
      <rect x="2" y="6" width="14" height="12" rx="2" />
    </svg>
  )
}
