/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/K3LXBoEFxZI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Rubik } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function Fusion() {
  return (
    <div className="flex min-h-[100dvh] flex-col bg-gradient-to-br from-[#F0F4F8] to-[#E5E9EF]">
      <header className="container mx-auto px-4 py-6 md:px-6 md:py-8">
        <nav className="flex items-center justify-between">
          <Link href="#" className="flex items-center space-x-2" prefetch={false}>
            <BotIcon className="h-6 w-6 text-primary" />
            <span className="text-lg font-semibold">AI Training Center</span>
          </Link>
          <div className="hidden space-x-4 md:flex">
            <Link href="#" className="text-muted-foreground hover:text-primary" prefetch={false}>
              Home
            </Link>
            <Link href="#" className="text-muted-foreground hover:text-primary" prefetch={false}>
              Modules
            </Link>
            <Link href="#" className="text-muted-foreground hover:text-primary" prefetch={false}>
              Pricing
            </Link>
            <Link href="#" className="text-muted-foreground hover:text-primary" prefetch={false}>
              Contact
            </Link>
          </div>
          <Button>Get Started</Button>
        </nav>
      </header>
      <main className="flex-1">
        <section className="container mx-auto px-4 py-12 md:px-6 md:py-16 lg:py-20">
          <div className="grid gap-8 md:grid-cols-2 lg:gap-12">
            <div className="space-y-4">
              <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl md:text-5xl">
                Train Your Chatbot with Confidence
              </h1>
              <p className="text-muted-foreground md:text-lg">
                Our comprehensive AI training center provides the tools and resources you need to build intelligent
                chatbots that deliver exceptional customer experiences.
              </p>
              <Button>Get Started</Button>
            </div>
            <div className="relative">
              <img
                src="/placeholder.svg"
                alt="Hero Image"
                width={500}
                height={400}
                className="mx-auto rounded-xl object-cover shadow-lg"
              />
              <div className="absolute -bottom-6 -right-6 hidden rounded-xl bg-muted p-4 shadow-lg md:block">
                <div className="flex items-center space-x-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <p className="text-sm font-medium">John Doe</p>
                    <p className="text-xs text-muted-foreground">AI Training Specialist</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="container mx-auto px-4 py-12 md:px-6 md:py-16 lg:py-20">
          <div className="space-y-8 md:space-y-12">
            <div className="text-center">
              <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl md:text-4xl">
                Comprehensive Training Modules
              </h2>
              <p className="mt-2 text-muted-foreground md:text-lg">
                Explore our wide range of training modules to build your chatbots capabilities.
              </p>
            </div>
            <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
              <div className="rounded-xl bg-white p-6 shadow-lg">
                <MessageCircleIcon className="h-8 w-8 text-primary" />
                <h3 className="mt-4 text-lg font-semibold">Conversational AI</h3>
                <p className="mt-2 text-muted-foreground">
                  Train your chatbot to engage in natural, human-like conversations.
                </p>
              </div>
              <div className="rounded-xl bg-white p-6 shadow-lg">
                <DatabaseIcon className="h-8 w-8 text-primary" />
                <h3 className="mt-4 text-lg font-semibold">Data Integration</h3>
                <p className="mt-2 text-muted-foreground">
                  Seamlessly integrate your chatbot with various data sources.
                </p>
              </div>
              <div className="rounded-xl bg-white p-6 shadow-lg">
                <LightbulbIcon className="h-8 w-8 text-primary" />
                <h3 className="mt-4 text-lg font-semibold">Intelligent Reasoning</h3>
                <p className="mt-2 text-muted-foreground">
                  Equip your chatbot with advanced reasoning and problem-solving capabilities.
                </p>
              </div>
              <div className="rounded-xl bg-white p-6 shadow-lg">
                <ShieldIcon className="h-8 w-8 text-primary" />
                <h3 className="mt-4 text-lg font-semibold">Security &amp; Privacy</h3>
                <p className="mt-2 text-muted-foreground">
                  Ensure your chatbot adheres to strict security and privacy standards.
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted py-8">
        <div className="container mx-auto px-4 md:px-6">
          <div className="flex flex-col items-center justify-between space-y-4 md:flex-row md:space-y-0">
            <div className="flex items-center space-x-2">
              <BotIcon className="h-6 w-6 text-primary" />
              <span className="text-lg font-semibold">AI Training Center</span>
            </div>
            <div className="flex space-x-4 text-muted-foreground">
              <Link href="#" className="hover:text-primary" prefetch={false}>
                Privacy
              </Link>
              <Link href="#" className="hover:text-primary" prefetch={false}>
                Terms
              </Link>
              <Link href="#" className="hover:text-primary" prefetch={false}>
                Contact
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

function BotIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 8V4H8" />
      <rect width="16" height="12" x="4" y="8" rx="2" />
      <path d="M2 14h2" />
      <path d="M20 14h2" />
      <path d="M15 13v2" />
      <path d="M9 13v2" />
    </svg>
  )
}


function DatabaseIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  )
}


function LightbulbIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5" />
      <path d="M9 18h6" />
      <path d="M10 22h4" />
    </svg>
  )
}


function MessageCircleIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>
  )
}


function ShieldIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
    </svg>
  )
}
