/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kihrghiqn98
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function GeneralSettings() {
  return (
    <div className="flex flex-col w-full min-h-screen">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <Link href="#" className="flex items-center gap-2 text-lg font-semibold sm:text-base mr-4" prefetch={false}>
          <FrameIcon className="w-6 h-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="hidden font-medium sm:flex flex-row items-center gap-5 text-sm lg:gap-6">
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Projects
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Deployments
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Analytics
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Logs
          </Link>
          <Link href="#" className="font-bold" prefetch={false}>
            Settings
          </Link>
        </nav>
        <div className="flex items-center w-full gap-4 md:ml-auto md:gap-2 lg:gap-4">
          <Button variant="ghost" size="icon" className="rounded-full ml-auto">
            <img src="/placeholder.svg" width="32" height="32" className="rounded-full border" alt="Avatar" />
            <span className="sr-only">Toggle user menu</span>
          </Button>
        </div>
      </header>
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] bg-muted/40 flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <div className="max-w-6xl w-full mx-auto grid gap-2">
          <h1 className="font-semibold text-3xl">General Settings</h1>
        </div>
        <div className="grid md:grid-cols-[180px_1fr] lg:grid-cols-[250px_1fr] items-start gap-6 max-w-6xl w-full mx-auto">
          <nav className="text-sm text-muted-foreground grid gap-4">
            <Link href="#" className="font-semibold text-primary" prefetch={false}>
              General
            </Link>
            <Link href="#" prefetch={false}>
              Domains
            </Link>
            <Link href="#" prefetch={false}>
              Log Drains
            </Link>
            <Link href="#" prefetch={false}>
              Webhooks
            </Link>
            <Link href="#" prefetch={false}>
              Integrations
            </Link>
            <Link href="#" prefetch={false}>
              Security
            </Link>
            <Link href="#" prefetch={false}>
              Advanced
            </Link>
          </nav>
          <div className="grid gap-6">
            <Card>
              <CardHeader>
                <CardTitle>Site Title</CardTitle>
                <CardDescription>
                  The title of your website, which will be displayed in the browser tab and search engine results.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <form>
                  <Input placeholder="Enter site title" />
                </form>
              </CardContent>
              <CardFooter className="border-t p-6">
                <Button>Save</Button>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Site Description</CardTitle>
                <CardDescription>
                  A brief description of your website, which will be displayed in search engine results.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <form>
                  <Textarea placeholder="Enter site description" rows={3} />
                </form>
              </CardContent>
              <CardFooter className="border-t p-6">
                <Button>Save</Button>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Favicon</CardTitle>
                <CardDescription>The small icon displayed in the browser tab and bookmarks.</CardDescription>
              </CardHeader>
              <CardContent>
                <form className="flex items-center gap-4">
                  <img src="/placeholder.svg" width="32" height="32" alt="Favicon" className="rounded" />
                  <Button variant="outline">Upload New Favicon</Button>
                </form>
              </CardContent>
              <CardFooter className="border-t p-6">
                <Button>Save</Button>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Logo</CardTitle>
                <CardDescription>The main logo displayed on your website.</CardDescription>
              </CardHeader>
              <CardContent>
                <form className="flex items-center gap-4">
                  <img src="/placeholder.svg" width="100" height="50" alt="Logo" className="rounded" />
                  <Button variant="outline">Upload New Logo</Button>
                </form>
              </CardContent>
              <CardFooter className="border-t p-6">
                <Button>Save</Button>
              </CardFooter>
            </Card>
          </div>
        </div>
      </main>
    </div>
  )
}

function FrameIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="22" x2="2" y1="6" y2="6" />
      <line x1="22" x2="2" y1="18" y2="18" />
      <line x1="6" x2="6" y1="2" y2="22" />
      <line x1="18" x2="18" y1="2" y2="22" />
    </svg>
  )
}
