/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6cWbqhCyDPT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Comfortaa } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function IrregularBgPractice() {
  return ( 
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1 flex items-center justify-center bg-background">
        <div className="relative w-full max-w-6xl px-4 md:px-6 lg:px-8 py-12 md:py-24 lg:py-32">
          <div className="absolute inset-0 -z-10 bg-muted rounded-[3rem] sm:rounded-[4rem] md:rounded-[5rem] lg:rounded-[6rem] xl:rounded-[7rem] overflow-hidden">
            <div className="absolute inset-0 bg-[#0f0f0f] rounded-[3rem] sm:rounded-[4rem] md:rounded-[5rem] lg:rounded-[6rem] xl:rounded-[7rem] rotate-[5deg] sm:rotate-[7deg] md:rotate-[9deg] lg:rotate-[11deg] xl:rotate-[13deg]" />
          </div>
          <div className="text-center space-y-4 md:space-y-6 lg:space-y-8">
            <h1 className="text-4xl font-bold tracking-tighter text-white sm:text-5xl md:text-6xl lg:text-7xl">
              Elevate Your Digital Presence
            </h1>
            <p className="text-lg text-gray-500 md:text-xl lg:text-2xl">
              Unlock the power of cutting-edge technology to transform your online experience.
            </p>
            <div className="flex justify-center gap-4">
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-6 text-sm font-medium text-white shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                Get Started
              </Link>
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-6 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                Learn More
              </Link>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
