/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/yrOSkjg3iEf
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Chivo } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { prisma } from "@/lib/connect"
import Link from "next/link"

export async function Team() {

  

  const teams= await prisma.user.findMany(
    {
      include:{
      bio:true
      }
    }
  )

  const organisationMember = teams.filter(team=>team.email.includes('gmail.com'))

  return (
    <div className='bg-white rounded-2xl p-6 m-6'>
    <h1 className=' font-extrabold text-4xl m-2'>
        Team
    </h1>
  <div className=' bg-gray-100 p-6 rounded-2xl'>
    <div className='grid grid-cols-1 gap-2 w-full'>
      {teams.map(member=>(
        <div key={member.id} className='flex bg-[green] text-white p-4 rounded-2xl'>
        <div className=' h-fit'>
            <img src={`${member.image}`} alt="" className="w-20 h-20 shadow-2xl shadow-black rounded-full object-cover object-center" />
        </div>
        <div className='w-full'>
            <Link href={`/observer/profile/${member.id}`} className='text-5xl font-extrabold ml-5 hover:text-green-500'>{member.username}</Link>
            <div className='p-3 bg-white text-black ml-2 w-fit rounded-2xl'>
                <div>
                  <h2 className='font-bold'>Department : <span className="text-gray-500">{member.depName}</span></h2>
                </div>

                <div>
                      <h2 className='font-bold'>Role : <span className="text-gray-500">{member.role}</span></h2>
                  </div>
            </div>
        </div>
    </div>
      ))}
          
    </div>
  </div>
</div>
  )
}

function MountainIcon(props: React.JSX.IntrinsicAttributes & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
