import MarketSideBar from "@/components/Market-side-bar";
import { Metadata } from "next";
import 'react-quill/dist/quill.snow.css';

export const metadata: Metadata = {
  title: "poly-observer",
  description: "Generated by create next app",
  icons:'https://dct4life-files.s3.af-south-1.amazonaws.com/uploads/pologo.png'
};

export default function page({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className={`flex `}>
            <MarketSideBar />
            <div className="w-full ">
                {children}
            </div>
          
        </div>
  );
}
